(()=>{'use strict';
if(window.jspdf&&window.jspdf.jsPDF)return;
const enc=new TextEncoder();
const clean=v=>String(v??'').normalize('NFKD').replace(/[^ const clean=v=>String(v??'').normalize('NFKD').replace(/[^\x20-~const clean=v=>String(v??'').normalize('NFKD').replace(/[^\x20-\x7E\n]/g,c=>({'–':'-','—':'-','•':'*','’':"'",'“':'"','”':'"','✓':'OK'}[c]||''));
const esc=v=>clean(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const wrap=(text,max=90)=>{const out=[];for(const para of clean(text).split(/\n/)){let line='';for(const word of para.split(/\s+/)){if(!word)continue;const next=line?line+' '+word:word;if(next.length>max){if(line)out.push(line);line=word}else line=next}out.push(line)}return out.length?out:['']};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name||'ShaSha-document.pdf';a.rel='noopener';a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},60000)}
function buildPdf(pages,orientation){const landscape=orientation==='landscape';const W=landscape?842:595,H=landscape?595:842;const objects=[];const add=s=>{objects.push(s);return objects.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const fontBold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');const pageIds=[];const contentIds=[];
for(const page of pages){let stream='BT\n/F1 11 Tf\n0 g\n';const lines=[];for(const item of page){const txt=Array.isArray(item.text)?item.text:[item.text];let x=Number(item.x||18)*2.83465,y=H-Number(item.y||20)*2.83465;const size=Math.max(7,Number(item.size||11)),leading=size*1.35,fontKey=item.bold?'F2':'F1';for(const raw of txt){for(const ln of wrap(raw,Math.max(25,Math.floor((W-x-36)/(size*.52))))){lines.push(`/${fontKey} ${size} Tf ${x.toFixed(2)} ${y.toFixed(2)} Td (${esc(ln)}) Tj`);x=Number(item.x||18)*2.83465;y-=leading}}}stream+=lines.join('\n')+'\nET';const sid=add(`<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}\nendstream`);contentIds.push(sid);pageIds.push(add('PENDING'))}
const pagesId=objects.length+1;for(let i=0;i<pageIds.length;i++)objects[pageIds[i]-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 ${font} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;add(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let pdf='%PDF-1.4\n%SHASHA\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(enc.encode(pdf).length);pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`}const xref=enc.encode(pdf).length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
class jsPDF{constructor(opts={}){this.orientation=opts.orientation||'portrait';this.pages=[[]];this.page=0;this.size=11;this.bold=false}setFillColor(){return this}setTextColor(){return this}setDrawColor(){return this}setLineWidth(){return this}rect(){return this}roundedRect(){return this}line(){return this}setFontSize(n){this.size=Number(n)||11;return this}setFont(_family,style){this.bold=String(style||'').includes('bold');return this}text(value,x,y,opts={}){const vals=Array.isArray(value)?value:[value];this.pages[this.page].push({text:vals,x,y,size:this.size,bold:this.bold,align:opts.align||'left'});return this}splitTextToSize(value,width){return wrap(value,Math.max(25,Math.floor(Number(width||150)/2.2)))}addPage(){this.pages.push([]);this.page=this.pages.length-1;return this}save(name){try{download(buildPdf(this.pages,this.orientation),name)}catch(err){console.error('ShaSha PDF fallback failed',err);alert('The PDF could not be created. Please refresh and try again.')}return this}output(type){const blob=buildPdf(this.pages,this.orientation);return type==='blob'?blob:blob}}
window.jspdf={jsPDF};window.ShaShaPDF={version:'1.0-local-fallback',download};
})();