(()=>{'use strict';
if(window.jspdf&&window.jspdf.jsPDF)return;
const enc=new TextEncoder();
const replacements={'–':'-','—':'-','•':'*','’':"'",'“':'"','”':'"','✓':'OK','…':'...'};
const clean=value=>Array.from(String(value??'').normalize('NFKD')).map(ch=>{if(ch==='\n')return ch;const n=ch.charCodeAt(0);if(n>=32&&n<=126)return ch;return replacements[ch]||''}).join('');
const esc=value=>clean(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const wrap=(text,max=90)=>{const out=[];for(const para of clean(text).split('\n')){let line='';for(const word of para.split(/\s+/)){if(!word)continue;const next=line?line+' '+word:word;if(next.length>max){if(line)out.push(line);line=word}else line=next}out.push(line)}return out.length?out:['']};
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name||'ShaSha-document.pdf';a.rel='noopener';a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},60000)}
function buildPdf(pages,orientation){const landscape=orientation==='landscape';const W=landscape?842:595;const H=landscape?595:842;const objects=[];const add=value=>{objects.push(value);return objects.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const fontBold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');const pageIds=[];const contentIds=[];
for(const page of pages){let stream='BT\n/F1 11 Tf\n0 g\n';const commands=[];for(const item of page){const values=Array.isArray(item.text)?item.text:[item.text];let y=H-Number(item.y||20)*2.83465;const baseX=Number(item.x||18)*2.83465;const size=Math.max(7,Number(item.size||11));const leading=size*1.35;const fontKey=item.bold?'F2':'F1';for(const raw of values){for(const line of wrap(raw,Math.max(25,Math.floor((W-baseX-36)/(size*0.52))))){commands.push(`/${fontKey} ${size} Tf 1 0 0 1 ${baseX.toFixed(2)} ${y.toFixed(2)} Tm (${esc(line)}) Tj`);y-=leading}}}stream+=commands.join('\n')+'\nET';const streamId=add(`<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}\nendstream`);contentIds.push(streamId);pageIds.push(add('PENDING'))}
const pagesId=objects.length+1;for(let i=0;i<pageIds.length;i++)objects[pageIds[i]-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 ${font} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;add(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let pdf='%PDF-1.4\n%SHASHA\n';const offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(enc.encode(pdf).length);pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`}const xref=enc.encode(pdf).length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
class jsPDF{constructor(options={}){this.orientation=options.orientation||'portrait';this.pages=[[]];this.page=0;this.size=11;this.bold=false}setFillColor(){return this}setTextColor(){return this}setDrawColor(){return this}setLineWidth(){return this}rect(){return this}roundedRect(){return this}line(){return this}setFontSize(value){this.size=Number(value)||11;return this}setFont(_family,style){this.bold=String(style||'').includes('bold');return this}text(value,x,y,options={}){this.pages[this.page].push({text:Array.isArray(value)?value:[value],x,y,size:this.size,bold:this.bold,align:options.align||'left'});return this}splitTextToSize(value,width){return wrap(value,Math.max(25,Math.floor(Number(width||150)/2.2)))}addPage(){this.pages.push([]);this.page=this.pages.length-1;return this}save(name){try{download(buildPdf(this.pages,this.orientation),name)}catch(error){console.error('ShaSha PDF fallback failed',error);alert('The PDF could not be created. Please refresh and try again.')}return this}output(){return buildPdf(this.pages,this.orientation)}}
window.jspdf={jsPDF};window.ShaShaPDF={version:'1.1-local-fallback',download};
})();