(()=>{
'use strict';
const db=window.shashaDb,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],days=['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
let teacher=null,classes=[],enrolments=[],learners=[],assignments=[],results=[];
const show=(el,t,e=false)=>{el.textContent=t;el.classList.remove('hidden','error');if(e)el.classList.add('error')},hide=el=>el.classList.add('hidden'),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#login-form').classList.toggle('hidden',b.dataset.authTab!=='login');$('#signup-form').classList.toggle('hidden',b.dataset.authTab!=='signup');hide($('#auth-message'))});
$('#login-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),{error}=await db.auth.signInWithPassword({email:String(f.get('email')).trim(),password:f.get('password')});if(error)return show($('#auth-message'),error.message,true);boot()};
$('#signup-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),{data,error}=await db.auth.signUp({email:String(f.get('email')).trim(),password:f.get('password'),options:{data:{full_name:String(f.get('fullName')).trim()}}});if(error)return show($('#auth-message'),error.message,true);show($('#auth-message'),data.session?'Account created. Link your teacher record next.':'Account created. Confirm your email, then sign in.');if(data.session)boot()};
$('#sign-out').onclick=async()=>{await db.auth.signOut();location.reload()};$('#refresh').onclick=load;
$('#claim-account').onclick=async()=>{const{error}=await db.rpc('claim_teacher_account');if(error)return show($('#claim-message'),error.message,true);show($('#claim-message'),'Teacher record linked.');load()};
async function boot(){const{data:{session}}=await db.auth.getSession();if(!session){$('#auth-view').classList.remove('hidden');$('#portal-view').classList.add('hidden');return}$('#auth-view').classList.add('hidden');$('#portal-view').classList.remove('hidden');$('#identity').textContent=session.user.email;load()}
async function load(){const{data:{session}}=await db.auth.getSession();if(!session)return boot();const tr=await db.from('teachers').select('*').eq('profile_id',session.user.id).maybeSingle();if(tr.error)return show($('#page-message'),tr.error.message,true);teacher=tr.data;if(!teacher){$('#claim-panel').classList.remove('hidden');$('#workspace').classList.add('hidden');return}$('#claim-panel').classList.add('hidden');$('#workspace').classList.remove('hidden');const [cr,er,ar,rr]=await Promise.all([db.from('classes').select('*,subject_catalog(name)').eq('teacher_id',teacher.id).order('weekday').order('start_time'),db.from('learner_classes').select('*,learners(*)').eq('status','active'),db.from('assignments').select('*').eq('teacher_id',teacher.id).order('created_at',{ascending:false}),db.from('assessment_results').select('id,published,assessments!inner(teacher_id)').eq('assessments.teacher_id',teacher.id)]);const bad=[cr,er,ar,rr].find(x=>x.error);if(bad)return show($('#page-message'),bad.error.message,true);classes=cr.data||[];const ids=new Set(classes.map(c=>c.id));enrolments=(er.data||[]).filter(e=>ids.has(e.class_id));learners=[...new Map(enrolments.map(e=>[e.learners?.id,e.learners]).filter(x=>x[0])).values()];assignments=ar.data||[];results=rr.data||[];render()}
function classOptions(){return '<option value="">Select class</option>'+classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
function learnerOptions(classId){return '<option value="">Select learner</option>'+enrolments.filter(e=>!classId||e.class_id===classId).map(e=>`<option value="${e.learner_id}">${esc(e.learners?.full_name||'Learner')}</option>`).join('')}
function render(){$('#today').textContent=new Intl.DateTimeFormat('en-ZW',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());$('#teacher-name').textContent=teacher.full_name;$('#class-count').textContent=classes.length;$('#learner-count').textContent=learners.length;$('#assignment-count').textContent=assignments.length;$('#result-count').textContent=results.filter(r=>r.published).length;$('#classes').innerHTML=classes.length?classes.map(c=>`<article class="class-card"><small>${days[c.weekday]} · ${c.start_time.slice(0,5)}–${c.end_time.slice(0,5)}</small><h3>${esc(c.subject_catalog?.name||c.subject_code)}</h3><p>${esc(c.name)}</p><div class="class-meta"><span>${enrolments.filter(e=>e.class_id===c.id).length} learner(s)</span><span>${esc(c.academic_level)}</span></div>${c.meeting_url?`<a class="join" href="${esc(c.meeting_url)}" target="_blank" rel="noopener">Open class</a>`:''}</article>`).join(''):'<div class="notice">No classes assigned yet.</div>';$('#assignments').innerHTML=assignments.length?assignments.map(a=>`<article class="class-card"><small>${a.published?'Published':'Draft'} · ${a.due_at?new Date(a.due_at).toLocaleString('en-ZW'):'No deadline'}</small><h3>${esc(a.title)}</h3><p>${esc(classes.find(c=>c.id===a.class_id)?.name||'Class')}</p></article>`).join(''):'<div class="notice">No assignments created yet.</div>';$$('#assignment-form select[name="classId"],#attendance-form select[name="classId"],#result-form select[name="classId"]').forEach(s=>s.innerHTML=classOptions());syncLearners($('#attendance-form'));syncLearners($('#result-form'))}
function syncLearners(form){form.learnerId.innerHTML=learnerOptions(form.classId.value)}
$('#attendance-form').classId.onchange=e=>syncLearners(e.currentTarget.form);$('#result-form').classId.onchange=e=>syncLearners(e.currentTarget.form);
$('#assignment-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={class_id:f.get('classId'),teacher_id:teacher.id,title:String(f.get('title')).trim(),instructions:String(f.get('instructions')).trim()||null,due_at:f.get('dueAt')?new Date(f.get('dueAt')).toISOString():null,max_score:Number(f.get('maxScore')),published:f.get('published')==='on'};const{error}=await db.from('assignments').insert(payload);if(error)return show($('#assignment-message'),error.message,true);show($('#assignment-message'),'Assignment saved successfully.');e.currentTarget.reset();load()};
$('#attendance-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={class_id:f.get('classId'),learner_id:f.get('learnerId'),lesson_date:f.get('lessonDate'),status:f.get('status'),note:String(f.get('note')).trim()||null,recorded_by:(await db.auth.getSession()).data.session.user.id};const{error}=await db.from('attendance_records').upsert(payload,{onConflict:'class_id,learner_id,lesson_date'});if(error)return show($('#attendance-message'),error.message,true);show($('#attendance-message'),'Attendance saved.');e.currentTarget.reset();render()};
$('#result-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),published=f.get('published')==='on';const assessment={class_id:f.get('classId'),teacher_id:teacher.id,title:String(f.get('title')).trim(),assessment_type:f.get('type'),assessment_date:new Date().toISOString().slice(0,10),max_score:Number(f.get('maxScore')),published};const ar=await db.from('assessments').insert(assessment).select('id').single();if(ar.error)return show($('#result-message'),ar.error.message,true);const user=(await db.auth.getSession()).data.session.user.id;const rr=await db.from('assessment_results').insert({assessment_id:ar.data.id,learner_id:f.get('learnerId'),score:Number(f.get('score')),feedback:String(f.get('feedback')).trim()||null,published,recorded_by:user});if(rr.error)return show($('#result-message'),rr.error.message,true);show($('#result-message'),'Result saved and '+(published?'published.':'kept private.'));e.currentTarget.reset();load()};
db.auth.onAuthStateChange(()=>setTimeout(boot,0));boot();
})();